package gov.ca.water.calgui.presentation;

import java.awt.Component;

import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JSlider;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import org.apache.log4j.Logger;
import org.swixml.SwingEngine;

import gov.ca.water.calgui.bus_service.impl.BatchRunSvcImpl;
import gov.ca.water.calgui.bus_service.impl.XMLParsingSvcImpl;

/**
 * This class is for Listening all the change events which are generated by the
 * application.(We only use this for "Regulations" tab)
 *
 * @author Mohan
 */
public class GlobalChangeListener implements ChangeListener {

	private static final Logger LOG = Logger.getLogger(GlobalChangeListener.class.getName());
	private SwingEngine swingEngine = XMLParsingSvcImpl.getXMLParsingSvcImplInstance().getSwingEngine();

	@Override
	public void stateChanged(ChangeEvent changeEvent) {
		String lcName = ((Component) changeEvent.getSource()).getName().toLowerCase();
		LOG.debug(lcName);
		if (lcName.equals("reg_tabbedpane")) {
			((JComponent) swingEngine.find("scrRegValues")).setVisible(false);
			((JPanel) swingEngine.find("reg_panTab")).setBorder(BorderFactory.createTitledBorder("Values"));
			boolean showTablePanel = ((JRadioButton) swingEngine.find("rdbRegQS_UD")).isSelected();
			// Hide/show reg_panTab as needed and selected - will be updated by
			// focus control
			((JPanel) this.swingEngine.find("reg_panTab")).setVisible(showTablePanel);
			((JPanel) this.swingEngine.find("reg_panTabPlaceholder")).setVisible(!showTablePanel);

		} else if (lcName.equals("run_sldthreads")) {
			BatchRunSvcImpl.simultaneousRuns = ((JSlider) changeEvent.getSource()).getValue();
			((JLabel) swingEngine.find("run_lblThreads")).setText(" " + BatchRunSvcImpl.simultaneousRuns + " run"
					+ ((BatchRunSvcImpl.simultaneousRuns > 1) ? "s" : ""));
		}
	}
}