package gov.ca.water.calgui.presentation;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Arrays;
import java.util.List;

import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

import org.apache.log4j.Logger;
import org.swixml.SwingEngine;

import gov.ca.water.calgui.bus_delegate.IApplyDynamicConDele;
import gov.ca.water.calgui.bus_delegate.impl.ApplyDynamicConDeleImp;
import gov.ca.water.calgui.bus_service.IDynamicControlSvc;
import gov.ca.water.calgui.bus_service.IResultSvc;
import gov.ca.water.calgui.bus_service.impl.DynamicControlSvcImpl;
import gov.ca.water.calgui.bus_service.impl.ResultSvcImpl;
import gov.ca.water.calgui.bus_service.impl.XMLParsingSvcImpl;
import gov.ca.water.calgui.tech_service.IAuditSvc;
import gov.ca.water.calgui.tech_service.impl.AuditSvcImpl;

/**
 * This class is for Listening all the item events(radio button, check box) which are generated by the application.
 *
 * @author mohan
 *
 */
public class GlobalItemListener implements ItemListener {

	private static final Logger LOG = Logger.getLogger(GlobalItemListener.class.getName());
	private IApplyDynamicConDele applyDynamicConDele = new ApplyDynamicConDeleImp();
	private SwingEngine swingEngine = XMLParsingSvcImpl.getXMLParsingSvcImplInstance().getSwingEngine();
	private IDynamicControlSvc dynamicControlSvc = DynamicControlSvcImpl.getDynamicControlSvcImplInstance();
	private IAuditSvc auditSvc = AuditSvcImpl.getAuditSvcImplInstance();
	private IResultSvc resultSvc = ResultSvcImpl.getResultSvcImplInstance();
	private String oldValue = "";
	/*
	 * we use the rollBackFlag when we show the popup box and user select the cancel at that time we use it to avoid the cascade
	 * effact.
	 */
	private boolean rollBackFlag = false;

	@Override
	public void itemStateChanged(ItemEvent ie) {
		if (resultSvc.isCLSFileLoading())
			return;
		if (dynamicControlSvc.isPreventRoeTrigger())
			return;
		String itemName = ((JComponent) ie.getItem()).getName();
		LOG.debug(itemName);
		boolean isSelected = ie.getStateChange() == ItemEvent.SELECTED;
		boolean isEnabled = ((JComponent) ie.getItem()).isEnabled();
		boolean optionFromTheBox = false;
		if (!rollBackFlag) {
			/*
			 * The following code is used for the spical case where we show popup box for some controls in the "Run Setting" and
			 * "Hydroclimate" tabs.
			 */
			List<String> controlIdForDialogBox = Arrays.asList("run_rdbD1485", "run_rdbD1641", "run_rdbBO", "hyd_rdb2005",
			        "hyd_rdb2030");
			List<String> controlIdOfCPP = Arrays.asList("hyd_rdbCCEL", "hyd_rdbCCLL", "hyd_ckb1", "hyd_ckb2", "hyd_ckb3",
			        "hyd_ckb4", "hyd_ckb5");
			List<String> controlIdForOldValue = Arrays.asList("run_rdbD1485", "run_rdbD1641", "run_rdbBO", "hyd_rdb2005",
			        "hyd_rdb2030", "hyd_rdbCCEL", "hyd_rdbCCLL");
			if (controlIdForOldValue.contains(itemName)) {
				if (!isSelected)
					oldValue = itemName;
			}
			if (controlIdForDialogBox.contains(itemName)) {
				if (isSelected) {
					int option = JOptionPane.showConfirmDialog(null, "You have selected " + ((JRadioButton) ie.getItem()).getText()
					        + ".\n  Do you wish to use the WSI/DI curves for this configuration?");
					if (option == JOptionPane.CANCEL_OPTION) {
						rollBackFlag = true;
						((JRadioButton) swingEngine.find(oldValue)).setSelected(true);
						rollBackFlag = false;
						return;
					} else if (option == JOptionPane.YES_OPTION) {
						optionFromTheBox = true;
					}
				}
			} else if (controlIdOfCPP.contains(itemName)) {
				if (isSelected)
					optionFromTheBox = true;
			}
		}
		if (isEnabled) {
			applyDynamicConDele.applyDynamicControl(itemName, isSelected, isEnabled, optionFromTheBox);
		}
		auditSvc.addAudit(itemName, String.valueOf(!isSelected), String.valueOf(isSelected));
	}
}